/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;
import javax.swing.JOptionPane;
import Formulario.login;
import java.beans.Statement;
/**
 *
 * @author ALEX HP
 */
public class Login extends javax.swing.JFrame {
Statement  stmt = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTUsuario = new javax.swing.JTextField();
        jPContraseña = new javax.swing.JPasswordField();
        jBIngresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(329, 230));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsuarioActionPerformed(evt);
            }
        });
        jTUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 152, -1));

        jPContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPContraseñaActionPerformed(evt);
            }
        });
        jPContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPContraseñaKeyPressed(evt);
            }
        });
        getContentPane().add(jPContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, -1));

        jBIngresar.setBackground(new java.awt.Color(0, 102, 255));
        jBIngresar.setText("Ingresar");
        jBIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });
        jBIngresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBIngresarKeyPressed(evt);
            }
        });
        getContentPane().add(jBIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/user_84308.png"))); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/key-silhouette-security-tool-interface-symbol-of-password_icon-icons.com_54503.png"))); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/fondo-abstracto-1.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
      ingresar(); 
    }//GEN-LAST:event_jBIngresarActionPerformed

    private void jTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsuarioActionPerformed
     
    }//GEN-LAST:event_jTUsuarioActionPerformed

    private void jPContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPContraseñaActionPerformed
       
    }//GEN-LAST:event_jPContraseñaActionPerformed

    private void jTUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTUsuarioKeyPressed
       if(evt.VK_TAB == evt.getKeyCode()|| evt.VK_ENTER == evt.getKeyCode()){
            jPContraseña.requestFocus();
        }
    }//GEN-LAST:event_jTUsuarioKeyPressed

    private void jPContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPContraseñaKeyPressed
         if(evt.VK_TAB == evt.getKeyCode()){
            jBIngresar.requestFocus();
        }
        if(evt.VK_ENTER==evt.getKeyCode()){
           ingresar();
        }
    }//GEN-LAST:event_jPContraseñaKeyPressed

    private void jBIngresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBIngresarKeyPressed
        if(evt.VK_ENTER==evt.getKeyCode()){
           ingresar();
        }
    }//GEN-LAST:event_jBIngresarKeyPressed
       public void ingresar(){
     login l =new login();
        boolean ingreso = l.Verificar(jTUsuario.getText(),jPContraseña.getText());
        if (jTUsuario.getText().equals("") ||  (jPContraseña.getText().equals(""))) { 
            JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",JOptionPane.INFORMATION_MESSAGE);
            jTUsuario.requestFocus();
           }
        else if(ingreso==true){
            this.setVisible(false);
         
       }
       else{
          JOptionPane.showMessageDialog(null,"Usuario/Contraseña Incorrecto \n","Error",JOptionPane.ERROR_MESSAGE);  
       }
       }
                                      

                                           

    
    
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPContraseña;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
